name: Release features
on:
  push:
    branches:
      - main

jobs:
  generate-documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Update README
        uses: devcontainers/action@v1
        with:
          base-path-to-features: "./src"
          generate-docs: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes
        id: push_image_info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          echo "Start."
          # Configure git and Push updates
          git config --global --add safe.directory /github/workspace
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
          git config pull.rebase false
          git fetch --depth=1 origin +refs/tags/*:refs/tags/* || true
          message='Automated documentation update'
          # Add / update and commit
          git add */**/README.md
          if [ "$(git status --porcelain | grep "$file" | grep -c -E '([MA]\W).+')" -eq 1 ]; then
            echo "::debug Added ${file} to git staging area"
          else
            echo "::debug No change in ${file} detected"
          fi
          echo "::debug Following files will be committed"
          git status -s
          git commit -m 'Automated documentation update [skip ci]' || export NO_UPDATES=true
          # Push
          if [ "$NO_UPDATES" != "true" ] ; then
              git push
          fi

  generate-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Publish Features
        uses: devcontainers/action@v1
        with:
          publish-features: "true"
          base-path-to-features: "./src"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
